---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Vagrant up
description: Start vagrant provisioning process
inputs:
  debug:
    description: "Enable debug level"
    default: false
  memory:
    description: "Memory"
    default: 12288
  os:
    description: "Operating System"
    default: ubuntu
  release:
    description: "Release"
    default: jammy
  vbox-controller:
    description: "VirtualBox Controller"
    default: "Virtual I/O Device SCSI controller"
  test-multinode:
    description: "Multinode test environment"
    default: false
  host-installer:
    description: "Run KRD deployment script on the host machine"
    default: false
  kube-version:
    description: "Kubernetes version"
  kubespray-version:
    description: "Kubespray version"
  cert-manager-enabled:
    description: "Enable Kubernetes Cert-Manager"
    default: false
  ingress-enabled:
    description: "Enable Kubernetes Ingress Controller"
    default: false
  container-runtime:
    description: "Container Runtime"
  kata-containers-enabled:
    description: "Enable Katacontainers"
    default: false
  crun-enabled:
    description: "Enable crun"
    default: false
  gvisor-enabled:
    description: "Enable gVisor"
    default: false
  youki-enabled:
    description: "Enable Youki"
    default: false
  metallb-enabled:
    description: "Enable MetalLB"
    default: false
  krew-plugins-list:
    description: "List of Krew plugins to be installed"
    default: " "
  docker-version:
    description: "Docker version"
  containerd-version:
    description: "ContainerD version"
  network-plugin:
    description: "CNI plugin"
    default: "flannel"
  enable-tests:
    description: "Enable KRD functional tests"
    default: false
  int-tests:
    description: "List of KRD integration tests"
  run-conformance-tools:
    description: "Run conformance tools"
    default: false
  run-benchmarks:
    description: "Run K6 and iperf networking benchmark tools"
    default: false
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/vagrant-setup
    - name: Bootstrap Kubernetes Nodes
      shell: bash
      env:
        VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
        DEBUG: ${{ inputs.debug }}
        MEMORY: ${{ inputs.memory }}
        OS: ${{ inputs.os }}
        RELEASE: ${{ inputs.release }}
        VBOX_CONTROLLER: ${{ inputs.vbox-controller }}
        TEST_MULTINODE: ${{ inputs.test-multinode }}
      working-directory: ./ci
      run: ./bootstrap.sh
    - name: Override All-in-One IP Address in Ansible Inventory
      if: inputs.host-installer == 'true' && inputs.test-multinode != 'true'
      shell: bash
      run: |
        ip=$(vagrant ssh-config aio | grep 'HostName' | awk '{print $2}' | tr '\\n' ' ' | tr -d '[:space:]')
        sed -i "s/10.10.16.3/$ip/g" inventory/hosts.ini
    - name: Deploy Kubernetes Cluster
      shell: bash
      env:
        VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
        DEBUG: ${{ inputs.debug }}
        HOST_INSTALLER: ${{ inputs.host-installer }}
        KRD_KUBE_VERSION: ${{ inputs.kube-version }}
        KRD_KUBESPRAY_VERSION: ${{ inputs.kubespray-version }}
        KRD_CERT_MANAGER_ENABLED: ${{ inputs.cert-manager-enabled }}
        KRD_INGRESS_NGINX_ENABLED: ${{ inputs.ingress-enabled }}
        KRD_CONTAINER_RUNTIME: ${{ inputs.container-runtime }}
        KRD_KATA_CONTAINERS_ENABLED: ${{ inputs.kata-containers-enabled }}
        KRD_CRUN_ENABLED: ${{ inputs.crun-enabled }}
        KRD_GVISOR_ENABLED: ${{ inputs.gvisor-enabled }}
        KRD_YOUKI_ENABLED: ${{ inputs.youki-enabled }}
        KRD_METALLB_ENABLED: ${{ inputs.metallb-enabled }}
        PKG_KREW_PLUGINS_LIST: ${{ inputs.krew-plugins-list }}
        KRD_DOCKER_VERSION: ${{ inputs.docker-version }}
        KRD_CONTAINERD_VERSION: ${{ inputs.containerd-version }}
        KRD_NETWORK_PLUGIN: ${{ inputs.network-plugin }}
      working-directory: ./ci
      run: ./provision_installer.sh
    - name: Run Assertions
      shell: bash
      env:
        HOST_INSTALLER: ${{ inputs.host-installer }}
        KRD_KUBE_VERSION: ${{ inputs.kube-version }}
        KRD_KUBESPRAY_VERSION: ${{ inputs.kubespray-version }}
        KRD_ENABLE_TESTS: ${{ inputs.enable-tests }}
        KRD_INT_TESTS: ${{ inputs.int-tests }}
        RUN_CONFORMANCE_TOOLS: ${{ inputs.run-conformance-tools }}
        KRD_KATA_CONTAINERS_ENABLED: ${{ inputs.kata-containers-enabled }}
        KRD_CRUN_ENABLED: ${{ inputs.crun-enabled }}
        KRD_GVISOR_ENABLED: ${{ inputs.gvisor-enabled }}
        KRD_YOUKI_ENABLED: ${{ inputs.youki-enabled }}
        RUN_BENCHMARKS: ${{ inputs.run-benchmarks }}
      working-directory: ./ci
      run: ./check.sh
    - name: Check HW resources
      if: failure()
      shell: bash
      run: |
        echo "===== SYSTEM ====="
        uptime
        echo "===== MEMORY ====="
        free -h
        vmstat 1 5
        cat /proc/meminfo | head -n 20
        echo "===== DISK ====="
        sudo df -h
        echo "===== VBOX LOGS ====="
        tail -n 200 ~/.config/VirtualBox/VBoxSVC.log 2>/dev/null || true
        echo "===== KERNEL ====="
        sudo dmesg -T | tail -n 100
