---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

version: 3

pullapprove_conditions:
  - '"base.ref" == "master"'
  - condition: "'*travis*' in statuses.successful"
    unmet_status: "failure"
    explanation: "Tests must pass before review starts"
notifications:
  - when: pull_request.opened
    if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
    comment: |
      Hey @{{ author }}, thanks for the PR! The review will start once
      the tests and CI checks have passed. If they don't, please review
      the logs and try to fix the issues (ask for help if you can't
      figure it out). A reviewer will be assigned once the tests are
      passing and they'll walk you through getting the PR finished
      and merged.
groups:
  code:
    reviewers:
      users:
        - electrocucaracha
    reviews:
      required: 1
      request: 1
      request_order: random
    labels:
      approved: "Code review approved"
