---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
rules:
  # yamllint disable-line rule:truthy
  prefer-kebab-case: off
external-tasks:
  - name: kubevirt
    uri: https://github.com/kubevirt/kubevirt-tekton-tasks
    path: release/tasks
