k8s.gcr.io/coredns:1.7.0
k8s.gcr.io/cpa/cluster-proportional-autoscaler-amd64:1.8.3
k8s.gcr.io/dns/k8s-dns-node-cache:1.17.1
k8s.gcr.io/ingress-nginx/controller:v0.43.0
k8s.gcr.io/kube-apiserver:$kube_version
k8s.gcr.io/kube-controller-manager:$kube_version
k8s.gcr.io/kube-proxy:$kube_version
k8s.gcr.io/kube-scheduler:$kube_version
quay.io/coreos/flannel:v0.13.0-amd64
quay.io/external_storage/local-volume-provisioner:v2.3.4
quay.io/jetstack/cert-manager-cainjector:v1.0.4
quay.io/jetstack/cert-manager-controller:v1.0.4
quay.io/jetstack/cert-manager-webhook:v1.0.4
