---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: apply virtlet extraRuntime label
  command: "/usr/local/bin/kubectl label node {{ item }} extraRuntime=virtlet --overwrite"
  with_inventory_hostnames: kube-node

- name: create Virtlet binary folder
  file:
    mode: '0755'
    state: directory
    path: "{{ virtlet_dest }}"

- name: generate image translations confimap file
  template:
    mode: preserve
    src: "images.yaml.j2"
    dest: "{{ virtlet_dest }}/images.yml"

- name: install image translations configmap
  shell: "/usr/local/bin/kubectl create configmap -n kube-system virtlet-image-translations --from-file {{ virtlet_dest }}/images.yml --dry-run -o yaml | /usr/local/bin/kubectl apply -f -"

- name: download virtletctl
  command: curl -Ls -o {{ virtlet_dest }}/virtletctl {{ virtlet_url }}  # noqa command-instead-of-module

- name: set virtletctl execution permissions
  file:
    path: "{{ virtlet_dest }}/virtletctl"
    mode: "+x"

- name: install virtletctl as kubectl plugin
  command: "mv {{ virtlet_dest }}/virtletctl /usr/local/bin/kubectl-virt"

- name: create Virtlet k8s objects
  shell: "/usr/local/bin/kubectl-virt gen | /usr/local/bin/kubectl apply -f -"

- name: wait for Virtlet daemonset
  shell: "/usr/local/bin/kubectl get ds virtlet -n=kube-system -o=jsonpath --template={.status.numberReady}"
  register: daemonset
  until:
    - '1'
  retries: 6
  delay: 10
