---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: boostrap servers
  hosts: all
  roles:
    - role: geerlingguy.docker
      docker_install_compose: false
      become: true
  tasks:
    - name: add existing user ansible's user to docker's group
      become: true
      ansible.builtin.user:
        name: '{{ ansible_ssh_user }}'
        groups: docker
        append: true
