---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: deploy cfssl binaries
  include: bootstrap.yml binary={{ item }}
  with_items:
    - cfssl
    - cfssljson

- name: ensure destination folder exists
  file:
    mode: '0755'
    state: directory
    path: "{{ pmem_template_folder }}"

- name: copy shell scripts
  copy:
    src: "{{ item }}"
    dest: "{{ pmem_template_folder }}/{{ item }}.sh"
    mode: +x
  with_items:
    - setup-ca-kubernetes
    - setup-ca

- name: get PMEM CSI node secret
  k8s_info:
    kind: Secret
    name: pmem-csi-node-secrets
    namespace: default
  register: node_secret

- name: get PMEM CSI registry secret
  k8s_info:
    kind: Secret
    name: pmem-csi-registry-secrets
    namespace: default
  register: registry_secret

- name: print node and registry values
  debug:
    var: '{{ item }}_secret'
  with_items:
    - node
    - registry

- name: create PMEM secrets
  become: true
  shell: 'PATH=$PATH:/usr/local/bin/ {{ pmem_template_folder }}/setup-ca-kubernetes.sh'
  args:
    chdir: '{{ pmem_template_folder }}'
  when:
    - node_secret.resources | length == 0
    - registry_secret.resources | length == 0

- name: create PMEM CSI for LVM driver
  k8s:
    state: present
    definition: "{{ lookup('template', 'pmem-csi-lvm.yaml.j2') }}"

- name: create PMEM storage classes
  k8s:
    state: present
    definition: "{{ lookup('file', 'pmem-{{ item }}.yaml') }}"  # noqa no-jinja-nesting
  with_items:
    - storageclass-ext4
    - storageclass-xfs
