---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-deployment
  labels:
    app: http-server
spec:
  replicas: 10
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: server
          image: openresty/openresty:1.21.4.1-2-alpine
          ports:
            - containerPort: 80
              name: server
          volumeMounts:
            - name: config
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes  1;
    events {
      worker_connections  4;
    }
    # max clients = worker_processes * worker_connections
    http {
      server {
        location /sleep {
          echo_sleep 0.01;
          echo_reset_timer;
          echo_location /;
          echo "took $echo_timer_elapsed sec for total.";
        }

        location / {
          root   /usr/local/openresty/nginx/html;
          index  index.html;
        }
      }
    }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    haproxy.org/path-rewrite: /
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: test.krd.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test
                port:
                  number: 8080
