---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-config
data:
  config: |
    import http from "k6/http";
    import { check } from "k6";
    export let options = {
      vus: 50,
      duration: "30s"
    };
    export default function() {
      const res = http.get(`http://${__ENV.TEST_SERVICE_HOST}:${__ENV.TEST_PORT_8080_TCP_PORT}/sleep`);
      check(res, {
        "status was 200": (r) => r.status == 200,
        "transaction time OK": (r) => r.timings.duration < 10
      });
    };
---
apiVersion: batch/v1
kind: Job
metadata:
  name: client
spec:
  template:
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: k6-test
          image: loadimpact/k6
          command: ["k6"]
          args: ["run", "/opt/script.js"]
          volumeMounts:
            - name: k6-volume
              mountPath: /opt/
      volumes:
        - name: k6-volume
          configMap:
            name: k6-config
            items:
              - key: config
                path: script.js
