---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: litellm-ollama-3-2
  namespace: kagent-system
spec:
  apiKeySecretKey: OPENAI_API_KEY
  apiKeySecretName: kagent-openai
  model: llama3.2
  provider: OpenAI
  openAI:
    baseUrl: http://nuc10-node08/litellm
---
apiVersion: v1
kind: Service
metadata:
  name: nuc10-node08
  namespace: kagent-system
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: nuc10-node08-01
  namespace: kagent-system
  labels:
    kubernetes.io/service-name: nuc10-node08
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "192.168.1.101"
