---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: litellm-ollama-3-2
  namespace: kagent-system
spec:
  apiKeySecretKey: OPENAI_API_KEY
  apiKeySecretName: kagent-openai
  model: llama3.2
  provider: OpenAI
  openAI:
    baseUrl: http://litellm-service.litellm-system.svc.cluster.local:4000/litellm
