---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: ollama-llama3-2
  namespace: kagent
spec:
  apiKeySecretKey: ""
  apiKeySecretRef: ""
  model: llama3.2
  ollama:
    host: http://192.168.1.18:11434
  provider: Ollama
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-website-fetcher
  namespace: kagent
  labels:
    app: mcp-website-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-website-fetcher
  template:
    metadata:
      labels:
        app: mcp-website-fetcher
    spec:
      containers:
        - name: mcp-website-fetcher
          image: ghcr.io/electrocucaracha/mcp-website-fetcher:main
          imagePullPolicy: Always
          env:
            - name: TRANSPORT
              value: "streamable-http"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-website-fetcher
  namespace: kagent
spec:
  selector:
    app: mcp-website-fetcher
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: website-fetch-agent
  namespace: kagent
spec:
  description: This agent can use a single tool to retrieve the contents of a webpage.
  modelConfig: kagent/ollama-llama3-2
  systemMessage: |-
    You're a friendly and helpful agent that uses the fetch tool to retrieve webpage contents.

    # Instructions

    - If user question is unclear, ask for clarification before running any tools
    - Always be helpful and friendly
    - If you don't know how to answer the question DO NOT make things up
      respond with "Sorry, I don't know how to answer that" and ask the user to further clarify the question

    # Response format
    - ALWAYS format your response as Markdown
    - Your response will include a summary of actions you took and an explanation of the result
  tools:
    - type: McpServer
      mcpServer:
        toolServer: kagent/mcp-toolserver
        toolNames:
          - fetch
---
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-toolserver
  namespace: kagent
spec:
  description: Fetches a website and returns its content
  config:
    streamableHttp:
      sseReadTimeout: 5m0s
      timeout: 30s
      url: http://mcp-website-fetcher.kagent.svc.cluster.local/mcp
