---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-template
spec:
  dataVolumeTemplates:
    - metadata:
        name: ubuntu-dv
      spec:
        storage:
          volumeMode: Filesystem
        source:
          pvc:
            name: ubuntu-img-jammy
  runStrategy: Manual
  template:
    metadata:
      name: runner
    spec:
      terminationGracePeriodSeconds: 30
      domain:
        devices:
          filesystems:
            - name: runner-info
              virtiofs: {}
          disks:
            - name: os
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        cpu:
          cores: 2
        resources:
          requests:
            memory: 8G
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: ubuntu-dv
          name: os
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              mounts:
                - [ runner-info, /runner-info/, virtiofs, "rw,relatime,user=runner" ]
              runcmd:
                - "sudo runuser -l runner -c '/opt/runner/run.sh --jitconfig $(jq -r '.jitconfig' /runner-info/runner-info.json)'"
              power_state:
                delay: now
                mode: poweroff
                message: Runner completed
                timeout: 2
                condition: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-actions-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevirt-actions-runner
rules:
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachineinstances"]
    verbs: ["get", "watch", "list", "create", "delete"]
