---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config-file
  namespace: litellm-system
data:
  config.yaml: |
    model_list:
      - model_name: llama3.1:8b
        litellm_params:
          model: ollama/llama3.1:8b
          api_base: http://ollama-svr01:11434
      - model_name: llama3.2
        litellm_params:
          model: ollama/llama3.2
          api_base: http://ollama-svr01:11434
      - model_name: llama3.3
        litellm_params:
          model: ollama/llama3.3
          api_base: http://ollama-svr01:11434
      - model_name: qwen2.5
        litellm_params:
          model: ollama/qwen2.5
          api_base: http://ollama-svr01:11434
      - model_name: qwen2.5-coder:1.5b-base
        litellm_params:
          model: ollama/qwen2.5-coder:1.5b-base
          api_base: http://ollama-svr01:11434
      - model_name: mistral
        litellm_params:
          model: ollama/mistral
          api_base: http://ollama-svr01:11434
      - model_name: nomic-embed-text
        litellm_params:
          model: ollama/nomic-embed-text
          api_base: http://ollama-svr01:11434
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-svr01
  namespace: litellm-system
spec:
  ports:
    - name: http
      protocol: TCP
      port: 11434
      targetPort: 11434
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ollama-svr01-1
  namespace: litellm-system
  labels:
    kubernetes.io/service-name: ollama-svr01
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 11434
endpoints:
  - addresses:
      - "192.168.1.18"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  namespace: litellm-system
  labels:
    app: litellm
spec:
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm:main-v1.81.16.custm-auth.dev
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: litellm-db-cnpg-app
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: litellm-db-cnpg-app
                  key: password
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: litellm-db-cnpg-app
                  key: uri
            - name: DATABASE_NAME
              value: litellm
            - name: STORE_MODEL_IN_DB
              value: "True"
            - name: SERVER_ROOT_PATH
              value: /litellm
            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-secrets
                  key: LITELLM_MASTER_KEY
          args:
            - "--config"
            - "/etc/litellm/config.yaml"
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: config-volume
              mountPath: /etc/litellm
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: 4000
            initialDelaySeconds: 120
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
            initialDelaySeconds: 120
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config-file
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: litellm-service
  namespace: litellm-system
spec:
  selector:
    app: litellm
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
# NOTE: Enable "Local Network" access for Firefox and Chrome. In Mac System Settings > Privacy & Security > Local Network > Firefox (set to true)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-ingress
  namespace: litellm-system
  annotations:
    haproxy.org/path-rewrite: /
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/app-root: /litellm
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: litellm-service
                port:
                  number: 4000
            path: /
            pathType: Prefix
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm-db-cnpg
  namespace: litellm-system
spec:
  description: Postgres cluster for the litellm application
  instances: 1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: litellm
      owner: litellm
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
