---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: batch/v1
kind: Job
metadata:
  name: client
  namespace: k6
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6-test
          image: loadimpact/k6
          command: ["k6"]
          args: ["run", "/opt/script.js"]
          volumeMounts:
            - name: k6-volume
              mountPath: /opt/
      volumes:
        - name: k6-volume
          configMap:
            name: k6-config
            items:
              - key: config
                path: script.js
