---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-config
  namespace: k6
data:
  config: |
    import http from "k6/http";
    import { check, sleep } from "k6";
    export let options = {
      vus: 500,
      noConnectionReuse: true,
      duration: "1m"
    };
    export default function() {
      let res = http.get("http://test.k6.svc.cluster.local:8080");
      check(res, {
        "status was 200": (r) => r.status == 200,
        "transaction time OK": (r) => r.timings.duration < 200
      });
    };
