---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-deployment
  namespace: k6
  labels:
    app: http-server
spec:
  replicas: 10
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: server
          image: openresty/openresty:1.19.3.1-8-alpine
          ports:
            - containerPort: 80
              name: server
          volumeMounts:
            - name: config
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: k6
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: k6
data:
  nginx.conf: |
    worker_processes  1;
    events {
      worker_connections  4;
    }
    # max clients = worker_processes * worker_connections
    http {
      server {
        location / {
          root   /usr/local/openresty/nginx/html;
          index  index.html index.htm;
          echo_sleep 1;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-config
  namespace: k6
data:
  config: |
    import http from "k6/http";
    import { check, sleep } from "k6";
    export let options = {
      vus: 500,
      noConnectionReuse: true,
      duration: "1m"
    };
    export default function() {
      let res = http.get("http://test.k6.svc.cluster.local:8080");
      check(res, {
        "status was 200": (r) => r.status == 200,
        "transaction time OK": (r) => r.timings.duration < 200
      });
    };
