---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: create-ubuntu-jammy-runner
spec:
  pipelineRef:
    name: ubuntu-runner-deployer
  params:
    - name: RELEASE_NAME
      value: jammy
    - name: RELEASE_VERSION
      value: 22.04
  taskRunTemplate:
    serviceAccountName: ubuntu-runner-deployer-account
