---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: cleanup | get qat plugin pod name
  shell: /usr/local/bin/kubectl get pods | grep intel-qat-plugin | awk '{print $1}'
  register: intel_qat_plugin_pod

- name: cleanup | delete qat plugin daemonset
  command: "/usr/local/bin/kubectl delete daemonsets intel-qat-plugin --now --force --ignore-not-found"

- name: cleanup | wait for destroying qat plugin
  shell: "/usr/local/bin/kubectl rollout status daemonsets/intel-qat-plugin --timeout=5m"
