---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019,2023
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- name: Remove the PyYAML package
  ansible.builtin.package:
    name: python3-yaml
    state: absent
  when: ansible_distribution == 'Ubuntu'
- name: Install kubernetes python package
  ansible.builtin.pip:
    name: kubernetes
- name: Delete qat plugin daemonset
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: DaemonSet
    name: intel-qat-plugin
