---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- include: cleanup.yml

- name: ensure destination folder exists
  file:
    mode: '0755'
    state: directory
    path: "{{ qat_template_folder }}"

- name: generate QAT DPDK k8s resources based on templates
  template:
    mode: preserve
    src: plugin.yaml.j2
    dest: "{{ qat_template_folder }}/plugin.yml"
  when: qat_plugin_mode == "dpdk"

- name: generate QAT kernel k8s resources based on templates
  template:
    mode: preserve
    src: plugin_kernel_mode.yaml.j2
    dest: "{{ qat_template_folder }}/plugin.yml"
  when: qat_plugin_mode == "kernel"

- name: get QAT configmap files
  copy:
    mode: preserve
    src: configmap.yaml
    dest: "{{ qat_template_folder }}/configmap.yaml"

- name: create QAT k8s resources
  command: "/usr/local/bin/kubectl apply -f {{ qat_template_folder }}"
