---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: boostrap servers
  hosts: all
  vars:
    kind_dest: /usr/local/bin
  pre_tasks:
    - name: install python3 packages
      become: true
      ansible.builtin.package:
        name: python3
        state: present
      when: ansible_os_family == "RedHat"
    - name: enforce python3 for ansible
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3
    - name: Load krd variables
      ansible.builtin.include_vars:
        file: ../../../../krd-vars.yml
  roles:
    - role: andrewrothstein.kind
      kind_install_dir: '{{ kind_dest }}'
    - andrewrothstein.kubectl
    - role: geerlingguy.docker
      docker_install_compose: false
      become: true
    - role: geerlingguy.pip
      become: true
      vars:
        pip_install_packages:
          - kubernetes==23.6.0
          - openshift==0.13.1
  tasks:
    - name: add existing user ansible's user to docker's group
      become: true
      ansible.builtin.user:
        name: '{{ ansible_ssh_user }}'
        groups: docker
        append: true
    - name: get k8s clusters
      ansible.builtin.command: '{{ kind_dest }}/kind get clusters --quiet'
      register: kind_cluster
      failed_when: ( kind_cluster.rc not in [ 0, 1 ] )
    - name: print kind_cluster value
      ansible.builtin.debug:
        var: kind_cluster
    - name: create k8s cluster
      become: true
      ansible.builtin.command: '{{ kind_dest }}/kind create cluster --name molecule --wait=300s'
      when: not 'molecule' in kind_cluster.stdout
    - name: create kubeconfig folder
      ansible.builtin.file:
        mode: '0755'
        path: '{{ ansible_env.HOME }}/.kube/'
        state: directory
    - name: copy kubeconfig root file
      become: true
      ansible.builtin.copy:
        mode: preserve
        src: /root/.kube/config
        dest: '{{ ansible_env.HOME }}/.kube/config'
        remote_src: true
        owner: '{{ ansible_ssh_user }}'
        group: '{{ ansible_ssh_user }}'
    - name: label PMEM node
      ansible.builtin.command: kubectl label node molecule-control-plane storage=pmem
