---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Create qat folder
  ansible.builtin.file:
    mode: '0755'
    state: directory
    path: "{{ qat_driver_dest }}"

- name: Extract qat driver source code
  ansible.builtin.unarchive:
    mode: '0755'
    src: "{{ qat_driver_url }}"
    dest: "{{ qat_driver_dest }}"
    remote_src: true
    creates: "{{ qat_driver_dest }}/configure"

- name: Check if configure was executed
  ansible.builtin.stat:
    path: "{{ qat_driver_dest }}/config.log"
  register: configure_log

- name: Configure qat driver source code
  ansible.builtin.command: ./configure
  args:
    chdir: "{{ qat_driver_dest }}"
  register: configure
  when: not configure_log.stat.exists

- name: Check if there is a adf_ctl binary
  ansible.builtin.stat:
    path: /usr/local/bin/adf_ctl
  register: adf_ctl

- name: Build qat driver
  become: true
  make:
    chdir: "{{ qat_driver_dest }}"
    target: install
  when: not adf_ctl.stat.exists
  notify:
    - Start qat_service service
