---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Get service status
  ansible.builtin.service_facts:

- name: Stop qat_service service
  become: true
  ansible.builtin.service:
    name: qat_service
    state: stopped
  when: ansible_facts.services["qat_service.service"] is defined

- name: Get intel_qat kernel module dependencies
  ansible.builtin.shell: |
    set -o pipefail
    PATH=$PATH:/usr/sbin/:/sbin/ lsmod | grep "^intel_qat" | awk '{print $4}'
  args:
    executable: /bin/bash
  register: intel_qat_deps
  changed_when: false
  failed_when: (intel_qat_deps.rc not in [0, 1])

- name: Print intel_qat_deps value
  ansible.builtin.debug:
    var: intel_qat_deps

- name: Remove intel_qat kernel module dependencies
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  loop: "{{ intel_qat_deps.stdout_lines }}"

- name: Remove kernel module
  become: true
  community.general.modprobe:
    name: intel_qat
    state: absent
