---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: get service status
  service_facts:

- name: stop qat_service service
  become: true
  service:
    name: qat_service
    state: stopped
  when: ansible_facts.services["qat_service.service"] is defined

- name: get intel_qat kernel module dependencies
  shell: PATH=$PATH:/usr/sbin/:/sbin/ lsmod | grep "^intel_qat" | awk '{print $4}'
  register: intel_qat_deps
  changed_when: false

- name: print intel_qat_deps value
  debug:
    var: intel_qat_deps

- name: remove intel_qat kernel module dependencies
  become: true
  modprobe:
    name: "{{ item }}"
    state: absent
  loop: "{{ intel_qat_deps.stdout_lines }}"

- name: remove kernel module
  become: true
  modprobe:
    name: intel_qat
    state: absent
