---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Create SR-IOV k8s resources
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"  # noqa no-jinja-nesting
    namespace: kube-system
  with_items:
    - configMap
    - sriovdp-daemonset
