---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
qat_plugin_tmpl_dir: /tmp/qat_k8s
qat_plugin_version: "0.17.0"
qat_plugin_mode: dpdk
