---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-monkey
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-monkey
    repoURL: https://asobti.github.io/kube-monkey/charts/repo
    targetRevision: v.0.5.3
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-monkey-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
