---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- name: Configure CRIU hosts
  hosts: criu
  roles:
    - role: geerlingguy.docker
  tasks:
    - name: Add ubuntu repo
      ansible.builtin.apt_repository:
        repo: ppa:criu/ppa
      when: ansible_os_family == 'Ubuntu'
    - name: Add centos repo
      ansible.builtin.yum_repository:
        name: criu-el7
        description: Copr repo for criu-el7 owned by adrian
        baseurl: https://copr-be.cloud.fedoraproject.org/results/adrian/criu-el7/epel-7-$basearch/
        gpgcheck: true
        gpgkey: https://copr-be.cloud.fedoraproject.org/results/adrian/criu-el7/pubkey.gpg
      when: ansible_os_family == 'RedHat'
    - name: Enable docker experimental features
      become: true
      ansible.builtin.copy:
        mode: preserve
        dest: /etc/docker/daemon.json
        content: |
          {
            "experimental": true,
            "debug": true
          }
    - name: Configure docker client
      when: lookup('env', 'http_proxy') != "fooproxy" or lookup('env', 'https_proxy') != "fooproxy" or lookup('env', 'no_proxy') != "fooproxy"
      block:
        - name: Create docker config folder
          ansible.builtin.file:
            state: directory
            path: /root/.docker/
            mode: '0755'
        - name: Configure docker client to use proxy values
          ansible.builtin.template:
            mode: preserve
            dest: "/root/.docker/config.json"
            content: |
              {
                "proxies":
                {
                  "default":
                  {
                    "httpProxy": "{{ lookup('env', 'http_proxy') }}",
                    "httpsProxy": "{{ lookup('env', 'https_proxy') }}",
                    "noProxy": "{{ lookup('env', 'no_proxy') }}"
                  }
                }
              }
    - name: Install CRIU packages
      ansible.builtin.package:
        name: criu
        state: present
    - name: Reload docker service
      ansible.builtin.service:
        name: docker
        state: restarted

# TODO: Disable seccomp
