---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019 Intel Corporation
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: qat-node
  become: yes
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
  tasks:
    - name: Load krd variables
      include_vars:
        file: "{{ item }}"
      with_items:
        - krd-vars.yml
        - "{{ ansible_os_family }}.yml"
    - name: retrieve QAT driver
      get_url:
        url: "{{ qat_driver_url }}"
        dest: "/tmp/qat.tar.gz"
    - name: create qat folder
      file:
        state: directory
        path: "{{ qat_driver_dest }}"
    - name: extract qat driver source code
      unarchive:
        src: "/tmp/qat.tar.gz"
        dest: "{{ qat_driver_dest }}"
        remote_src: yes
    - name: RedHat | install build tools
      yum:
        name: "@Development tools"
        state: present
      when: ansible_os_family == 'RedHat'
    - name: install qat compilation packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ qat_driver_pkgs }}"
    - name: get kernel version
      shell: "uname -r"
      register: kernel_version
    - name: install kernel development tools
      package:
        name: "kernel-devel-{{ kernel_version.stdout }}"
        state: present
      when: ansible_os_family == 'RedHat'
    - name: stop qat_service service
      service:
        name: "qat_service"
        state: stopped
      ignore_errors: True
    - name: get intel_qat kernel module dependencies
      shell: lsmod | grep "^intel_qat" | awk '{print $4}'
      register: intel_qat_deps
    - name: remove intel_qat kernel module deps
      shell: rmmod {{ item }}
      with_items: "{{ intel_qat_deps.stdout.split(',') }}"
      ignore_errors: True
    - name: remove intel_qat kernel module
      shell: rmmod intel_qat
      ignore_errors: True
    - name: configure qat driver source code
      command: ./configure --enable-kapi
      args:
        chdir: "{{ qat_driver_dest }}"
    - name: build qat driver
      make:
        chdir: "{{ qat_driver_dest }}"
        target: "{{ item }}"
      loop:
        - clean
        - uninstall
        - install
    - name: create qat_service systemd wrapper
      blockinfile:
        path: /etc/systemd/system/qat_service.service
        create: yes
        block: |
          [Unit]
          Description=Intel QuickAssist Technology service

          [Service]
          Type=forking
          Restart=no
          TimeoutSec=5min
          IgnoreSIGPIPE=no
          KillMode=process
          GuessMainPID=no
          RemainAfterExit=yes
          ExecStart=/etc/init.d/qat_service start
          ExecStop=/etc/init.d/qat_service stop

          [Install]
          WantedBy=multi-user.target
    - name: reload qat_service service
      service:
        name: "qat_service"
        state: reloaded
    - name: start qat_service service
      service:
        name: "qat_service"
        state: started
        enabled: yes
