---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- import_playbook: configure-krd.yml

- hosts: localhost
  pre_tasks:
    - name: Load krd variables
      include_vars:
        file: krd-vars.yml
    - name: check if kubeclt was installed
      stat:
        path: /usr/local/bin/kubectl
      register: kubectl_lnk
  roles:
    - role: andrewrothstein.kubectl
      kubectl_ver: "v{{ kubectl_version }}"
      when: not kubectl_lnk.stat.exists
  tasks:
    - name: get sriov plugin pod name
      shell: /usr/local/bin/kubectl get pods -n kube-system| grep kube-sriov-device-plugin-amd64 | awk '{print $1}'
      register: intel_sriov_plugin_pods
    - name: delete sriov plugin daemonset
      command: "/usr/local/bin/kubectl delete ds/kube-sriov-device-plugin-amd64 -n kube-system --now --force"
      ignore_errors: True
    - name: wait for destroying sriov plugin
      shell: "/usr/local/bin/kubectl get pods {{ item }} -n kube-system"
      register: get_pod_result
      until: get_pod_result.rc == 0
      ignore_errors: True
      with_items: '{{ intel_sriov_plugin_pods.stdout_lines }}'
    - name: create SR-IOV k8s resources
      command: "/usr/local/bin/kubectl apply -f {{ sriov_plugin_url }}/{{ item }}.yaml"
      with_items:
        - configMap
        - sriovdp-daemonset
    - name: use sriov plugin stable docker image
      command: "/usr/local/bin/kubectl set image ds/kube-sriov-device-plugin-amd64 kube-sriovdp=nfvpe/sriov-device-plugin:{{ sriov_plugin_version }} -n kube-system"
    - name: change imagePolicy for kube-sriov-device-plugin-amd64
      command: "/usr/local/bin/kubectl -n kube-system edit ds/kube-sriov-device-plugin-amd64"
      environment:
        KUBE_EDITOR: "sed -i \"s|imagePullPolicy: .*|imagePullPolicy: Always|g\""
    - name: change daemonset update policy
      command: /usr/local/bin/kubectl patch ds/kube-sriov-device-plugin-amd64 -n kube-system -p='{"spec":{"updateStrategy":{"type":"RollingUpdate"}}}'  # noqa 206
