---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Molecule execution
inputs:
  tox-env:
    description: 'Python TOX environment'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
    - uses: syphar/restore-virtualenv@v1.2
      id: cache-tox-molecule
      with:
        requirement_files: test-requirements.txt
        custom_virtualenv_dir: .tox/molecule
    - name: Install Tox tool
      shell: bash
      run: brew install tox
    - uses: ./.github/actions/vagrant-setup
    - name: Run molecule tests
      shell: bash
      env:
        VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
        TOXENV: ${{ inputs.tox-env }}
      run: tox
