---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Molecule execution
description: Executes an Ansible molecule integration test
inputs:
  tox-env:
    description: "Python TOX environment"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # 6.1.0
      with:
        python-version: "3.x"
    - uses: syphar/restore-virtualenv@e536692e76315a068b4905f792e25febfe6d4391 # 1.3
      id: cache-tox-molecule
      with:
        requirement_files: test-requirements.txt
        custom_virtualenv_dir: .tox/molecule
    - uses: ./.github/actions/vagrant-setup
    - name: Install dependencies
      shell: bash
      run: pip install tox
    - name: Run molecule tests
      shell: bash
      env:
        VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
        VAGRANT_HOME: /tmp
        TOXENV: ${{ inputs.tox-env }}
      run: tox
