---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Molecule execution
inputs:
  tox-env:
    description: "Python TOX environment"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # 5.2.0
      with:
        python-version: "3.x"
    - uses: syphar/restore-virtualenv@e536692e76315a068b4905f792e25febfe6d4391 # 1.3
      id: cache-tox-molecule
      with:
        requirement_files: test-requirements.txt
        custom_virtualenv_dir: .tox/molecule
    - name: Install Tox tool
      shell: bash
      run: brew install tox
    - name: Install vagrant tool
      shell: bash
      run: brew install vagrant
    - uses: ./.github/actions/vagrant-setup
    - name: Run molecule tests
      shell: bash
      env:
        VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
        VAGRANT_HOME: /tmp
        TOXENV: ${{ inputs.tox-env }}
      run: tox
