---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Molecule execution
inputs:
  tox-env:
    description: 'Python TOX environment'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
    - uses: syphar/restore-virtualenv@v1.2
      id: cache-tox-molecule
      with:
        requirement_files: test-requirements.txt
        custom_virtualenv_dir: .tox/molecule
    - uses: actions/cache@v3
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('distros_supported.yml') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-
    - name: Apply workaround for VBoxHeadless issue on macOS (https://www.virtualbox.org/ticket/20636)
      shell: bash
      run: |
        if [[ "$(VBoxManage --version)" == "6.1.28r147628" ]]; then
            find playbooks/roles/ -type f -name "molecule.yml" -exec sed -i '.bak' 's|gui: .*|gui: True|g' {} \;
            find . -type f -name "*.bak" -delete
        fi
    - name: Install Tox tool
      shell: bash
      run: brew install tox
    - name: Run molecule tests
      shell: bash
      env:
        VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
        TOXENV: ${{ inputs.tox-env }}
      run: tox
