---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
contrib:
  agents:
    k8s:
      enabled: false
    istio:
      enabled: false
    helm:
      enabled: false
    observability:
      enabled: false
    argoRolloutsConversion:
      enabled: false
