---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Multus installation
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

jobs:
  check-multuss:
    runs-on: ubuntu-18.04
    env:
      KRD_DEBUG: true
      KRD_MULTUS_ENABLED: true
    steps:
      - uses: actions/checkout@v2
      - name: Deploy services
        run: KRD_FOLDER=$(git rev-parse --show-toplevel) ./aio.sh
      - name: Run Multus tests
        run: cd tests; ./multus.sh
      - name: Undeploy services
        run: ./krd_command.sh -a uninstall_k8s
