---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Security Toolsets
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**.sh'
      - '!ci/update_*.sh'
      - '*.yml'
      - '!playbooks/**/*.yml'
      - '*.tpl'
      - '*.env'
      - 'resources/*'
      - '!**.md'
  pull_request_review:
    types:
      - submitted
    paths:
      - '**.sh'
      - '!ci/update_*.sh'
      - '*.yml'
      - '!playbooks/**/*.yml'
      - '*.tpl'
      - '*.env'
      - 'resources/*'
      - '!**.md'

jobs:
  check-security-tools:
    name: Check K8s Plugins installation methods in an Ubuntu Bionic All-in-One setup
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    runs-on: macos-10.15
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
      MEMORY: 12288
      KRD_INGRESS_NGINX_ENABLED: false
      KRD_ENABLE_TESTS: true
      PKG_KREW_PLUGINS_LIST: "cert-manager"
    steps:
      - uses: actions/checkout@v3
      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-ubuntu-bionic-${{ hashFiles('distros_supported.yml') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-ubuntu-bionic-
      - name: Apply workaround for VBoxHeadless issue on macOS (https://www.virtualbox.org/ticket/20636)
        shell: bash
        run: |
          if [[ "$(VBoxManage --version)" == "6.1.28r147628" ]]; then
              find . -type f -iname "Vagrantfile" -exec sed -i '.bak' 's|v.gui = .*|v.gui = true|g' {} \;
              find . -type f -name "*.bak" -delete
          fi
      - name: Replace shorten links
        run: |
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_pkg|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/install.sh|g' {} \;
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_bin|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/bindep_install.sh|g' {} \;
          find . -type f -name "*.bak" -delete
      - name: Run integration tests
        env:
          KRD_INT_TESTS: "falco kyverno gatekeeper"
        run: |
          cd ci
          ./bootstrap.sh
          ./provision_installer.sh
          ./check.sh
      - name: Cleanup previous execution
        run: vagrant destroy -f
      - name: Run kubewarden integration tests
        env:
          KRD_INT_TESTS: "kubewarden"
          KRD_KUBE_VERSION: v1.21.6
          KRD_KUBESPRAY_VERSION: v2.17.1
          KRD_DOCKER_VERSION: latest
          KRD_CONTAINERD_VERSION: latest
        run: |
          cd ci
          ./bootstrap.sh
          ./provision_installer.sh
          ./check.sh
