---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Virtlet service
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - 'playbooks/roles/virtlet/**'
      - 'playbooks/roles/criproxy/**'
      - '!**.md'
  pull_request_review:
    types:
      - submitted
    paths:
      - 'playbooks/roles/virtlet/**'
      - 'playbooks/roles/criproxy/**'
      - '!**.md'

jobs:
  check-virtlet:
    name: Check Mirantis Virtlet solution in an Ubuntu Bionic All-in-One setup
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-ubuntu-bionic-${{ hashFiles('distros_supported.yml') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-ubuntu-bionic-
      - name: Replace shorten links
        run: |
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_pkg|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/install.sh|g' {} \;
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_bin|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/bindep_install.sh|g' {} \;
          find . -type f -name "*.bak" -delete
      - name: Run integration tests
        env:
          VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
          MEMORY: 12288
          KRD_KUBE_VERSION: v1.18.10
          KRD_KUBESPRAY_VERSION: v2.15.1
          KRD_CERT_MANAGER_ENABLED: false
          KRD_INGRESS_NGINX_ENABLED: false
          TEST_VIRTLET: true
          KRD_CONTAINER_RUNTIME: docker
        run: |
          cd ci
          ./bootstrap.sh
          ./provision_installer.sh
          ./check.sh
