---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Runtime Classes
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**.sh'
      - '!ci/update_*.sh'
      - '*.yml'
      - '!playbooks/**/*.yml'
      - '*.tpl'
      - '*.env'
      - 'resources/*'
      - '!**.md'
  pull_request_review:
    types:
      - submitted
    paths:
      - '**.sh'
      - '!ci/update_*.sh'
      - '*.yml'
      - '!playbooks/**/*.yml'
      - '*.tpl'
      - '*.env'
      - 'resources/*'
      - '!**.md'

jobs:
  check-runtimeclasses:
    name: Check Container Runtime Classes in an Ubuntu Focal All-in-One setup
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        include:
          - runtime: crio
            crun_enabled: true
          - runtime: containerd
            gvisor_enabled: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/vagrant-up
        with:
          container-runtime: ${{ matrix.runtime }}
          kata-containers-enabled: true
          crun-enabled: ${{ matrix.crun_enabled }}
          gvisor-enabled: ${{ matrix.gvisor_enabled }}
