---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Check Virtlet service
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "playbooks/roles/virtlet/**"
      - "playbooks/roles/criproxy/**"
      - "!**.md"
  pull_request_review:
    types:
      - submitted
jobs:
  check-virtlet:
    name: Check Mirantis Virtlet solution in an Ubuntu Bionic All-in-One setup
    if: >-
      ( github.event_name == 'pull_request_review' && github.event.review.state == 'approved' ) || github.event_name != 'pull_request_review'
    runs-on: vm-self-hosted
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - uses: ./.github/actions/vagrant-up
        with:
          kube-version: v1.18.17
          kubespray-version: v2.15.1
          cert-manager-enabled: false
          test-virtlet: true
          container-runtime: docker
          docker-version: latest
          containerd-version: latest
          release: bionic
