---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Scheduled verification
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            ./ci/update_versions.sh
            pip install pip-tools
            pip-compile test-requirements.in --output-file test-requirements.txt --upgrade
          COMMIT_MESSAGE: 'Upgrade galaxy requirements and krd versions files'
          COMMIT_NAME: 'electrocucaracha bot'
          PR_BRANCH_NAME: "versions-update-${PR_ID}"
          PR_TITLE: 'chore: update versions'
  check-dictionary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            sudo apt-get update
            sudo apt-get -y --no-install-recommends install aspell aspell-en
            pip install pyspelling

            sort --ignore-case --output=original.dic .github/.wordlist.txt
            echo "" > .github/.wordlist.txt
            # Remove leftovers
            pyspelling -c .spellcheck.yml | sed '/^<.*>/d;/^!!!/d;/^--/d;/^Misspelled words:/d;/^$/d;/^Spelling check passed :)$/d' | sort --ignore-case | uniq | tee draft.dic
            comm -12 --nocheck-order draft.dic original.dic > .github/.wordlist.txt
          COMMIT_MESSAGE: 'Update dictionary definitions'
          COMMIT_NAME: 'spellchecker bot'
          PR_BRANCH_NAME: "versions-update-${PR_ID}"
          PR_TITLE: 'chore: update dictionary'
