---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

dependency:
  name: galaxy
  options:
    role-file: ../../../galaxy-requirements.yml
    requirements-file: ../../../galaxy-requirements.yml
driver:
  name: vagrant
lint: |
  set -e
  PATH=${PATH}
  yamllint -c ../../../.yaml-lint.yml .
platforms:
  - name: centos7
    box: generic/centos7
    box_version: 4.1.10
    memory: 6144
    cpus: 2
    provider_options:
      gui: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--nictype1', 'virtio', '--cableconnected1', 'on']"
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
